version: '3'

networks:
  lumen-api:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: docker/images/phpfpm/Dockerfile
    tty: true
    restart: unless-stopped
    container_name: lumen-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - lumen-api

  nginx:
    image: 'nginx:alpine'
    container_name: lumen-nginx
    restart: unless-stopped
    tty: true
    ports:
      - '4999:80'
      - '443:443'
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - lumen-api

  rdb:
    image: postgres
    container_name: lumen-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: lumenapi
      MYSQL_DATABASE: lumenapi
      MYSQL_USER: lumenapi
      MYSQL_PASSWORD: lumenapi
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - lumen-api

  redis:
    image: redis:6.0-buster
    container_name: lumen-redis
    ports:
      - "6379:6379"
    networks:
      - lumen-api

#  clickhouse:
#    image: yandex/clickhouse-client
#    container_name: lumen-clickhouse
#    ports:
#      - "
