version: '3'

networks:
  lumen-api:
    driver: bridge

services:
  app:
    build:
      context: docker/images/app
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    container_name: lumen-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - redis
    env_file:
      - docker/images/app/.env
    networks:
      - lumen-api

  nginx:
    image: 'nginx:alpine'
    container_name: lumen-nginx
    restart: unless-stopped
    tty: true
    ports:
      - '8001:80'
      - '443:443'
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - lumen-api

  redis:
    image: redis:6.0-buster
    container_name: lumen-redis
    ports:
      - "6379:6379"
    networks:
      - lumen-api
